lr: 0.001
epochs: 30
batch_size: 128

experiment: shuffle_pose
dataset: dataset.pose7500.FasterPose7500

train_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/pose7500numpy/
  p_mat_dir: /mnt/hdd/wuxiao/DHP19/P_matrices/
  skeleton_dir: /mnt/hdd/wuxiao/DHP19/matlab_official/h5_dataset_7500_events/344x260/
  mode: train
  use_percentage: 100
  experiment: shuffle_pose
test_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/pose7500numpy/
  p_mat_dir: /mnt/hdd/wuxiao/DHP19/P_matrices/
  skeleton_dir: /mnt/hdd/wuxiao/DHP19/matlab_official/h5_dataset_7500_events/344x260/
  mode: test
  use_percentage: 100
  experiment: shuffle_pose

model: model.shufflenet_pose.ShuffleNet
model_args:
  in_channels: 1
  out_channels: 13
  width_mult: 0.5

optimizer: torch.optim.Adam
scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
scheduler_args:
  mode: min
  factor: 0.1
  patience: 5
  verbose: True

criterion: utils.losses.mse2D
metric: utils.losses.mpjpe
test_interval: 1
max_metric: False
trainer: utils.trainer.train
