lr: 0.001
epochs: 150
batch_size: 4

experiment: action
dataset: dataset.action.Action

train_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/event_high_frame/
  mode: train
  cameras:
   - 2
   - 3
  downsample_step: 10
  events_per_frame: 7500
  window_size: 100
  step_size: 50
  use_percentage: 15

test_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/event_high_frame/
  mode: test
  cameras:
   - 2
   - 3
  downsample_step: 10
  events_per_frame: 7500
  window_size: 100
  step_size: 50
  use_percentage: 15
model: model.action.DeepLSTM
model_args:
  arch: GRU
  fc_size:
    - 1024
    - 1024
    - 26
  num_classes: 33
  paths:
    - feat
    - heat
    - pose
  pretrain_pth: /mnt/hdd/wuxiao/winter/checkpoints/mm_cnn/1126_21:13:34_model.pt
  arch_option: 1
  mean_after_fc: True
optimizer: torch.optim.Adam
scheduler: torch.optim.lr_scheduler.ReduceLROnPlateau
scheduler_args:
  mode: min
  factor: 0.1
  patience: 100
  verbose: True

criterion: torch.nn.functional.cross_entropy
metric: utils.losses.accuracy
max_metric: True
trainer: utils.trainer.train

stages:
 - {epoch: 0, operation: fix_cnn}
 - {epoch: 40, operation: unfix_cnn}
 