lr: 0.001
epochs: 35
batch_size: 32

experiment: pose7500
dataset: dataset.pose7500.FasterPose7500

train_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/new_pose_numpy/
  p_mat_dir: /mnt/hdd/wuxiao/DHP19/P_matrices/
  skeleton_dir: /mnt/hdd/wuxiao/DHP19/matlab_official/h5_dataset_7500_events/344x260/
  mode: train
  experiment: dhpcnn

test_dataset_args:
  data_dir: /mnt/hdd/wuxiao/DHP19/new_pose_numpy/
  p_mat_dir: /mnt/hdd/wuxiao/DHP19/P_matrices/
  skeleton_dir: /mnt/hdd/wuxiao/DHP19/matlab_official/h5_dataset_7500_events/344x260/
  mode: test
  experiment: dhpcnn

model: model.pose7500.DHP_CNN
model_args:
  input_size:
    - 1
    - 260
    - 344
optimizer: torch.optim.RMSprop
scheduler: torch.optim.lr_scheduler.MultiStepLR
scheduler_args:
  milestones: 
    - 15
    - 25

criterion: utils.losses.mse2D
metric: utils.losses.mpjpe
test_interval: 1
max_metric: False
trainer: utils.trainer.train